language: node_js
node_js:
  - 14

cache:
  directories:
    "node_modules"

script:
  - eslint 'src/**'
  - yarn run test:coverage
  - yarn run test:report

after_success:
  - curl -Os https://uploader.codecov.io/latest/linux/codecov
  - chmod +x codecov
  - ./codecov
