import { Artist } from "./Artist";
import { Copyright } from "./Copyright";
import { ExternalIDS } from "./ExternalIDS";
import { ExternalUrls } from "./ExternalUrls";
import { Image } from "./Image";
import { PagingTracks } from "./Paging";
// Generated by https://quicktype.io

export class Album {
  public album_type: string;
  public artists: Artist[];
  public available_markets: string[];
  public copyrights: Copyright[];
  public external_ids: ExternalIDS;
  public external_urls: ExternalUrls;
  public genres: any[];
  public href: string;
  public id: string;
  public images: Image[];
  public name: string;
  public popularity: number;
  public release_date: string;
  public release_date_precision: string;
  public tracks: PagingTracks;
  public type: string;
  public uri: string;

  constructor(response: any) {
    this.album_type = response.album_type;
    this.artists = response.artists;
    this.available_markets = response.available_markets;
    this.copyrights = response.available_markets;
    this.external_ids = response.external_ids;
    this.external_urls = response.external_urls;
    this.genres = response.genres;
    this.href = response.href;
    this.id = response.id;
    this.images = response.images;
    this.name = response.name;
    this.popularity = response.popularity;
    this.release_date = response.release_date;
    this.release_date_precision = response.release_date_precision;
    this.tracks = response.tracks;
    this.type = response.type;
    this.uri = response.uri;
  }
}
