import { SimplifiedArtist } from "./Artist";
import { Copyright } from "./Copyright";
import { ExternalIDS } from "./ExternalIDS";
import { ExternalUrls } from "./ExternalUrls";
import { Image } from "./Image";
import { PagingTracks, PagingAlbums } from "./Paging";
// Generated by https://quicktype.io

export interface FeaturedAlbums {
  message: string;
  albums: PagingAlbums;
}

export interface SimplifiedAlbum {
  album_group?: string;
  album_type: string;
  artists: SimplifiedArtist[];
  available_markets: string[];
  external_urls: ExternalUrls;
  href: string;
  id: string;
  images: Image[];
  name: string;
  release_date: string;
  release_date_precision: string;
  restrictions: any;
  type: string;
  uri: string;
}

export class Album implements SimplifiedAlbum {
  public album_type: string;
  public artists: SimplifiedArtist[];
  public available_markets: string[];
  public copyrights: Copyright[];
  public external_ids: ExternalIDS;
  public external_urls: ExternalUrls;
  public genres: any[];
  public href: string;
  public id: string;
  public images: Image[];
  public name: string;
  public release_date: string;
  public release_date_precision: string;
  public restrictions: any;
  public popularity: number;
  public tracks: PagingTracks;
  public type: string;
  public uri: string;

  constructor(response: any) {
    this.album_type = response.album_type;
    this.artists = response.artists;
    this.available_markets = response.available_markets;
    this.copyrights = response.available_markets;
    this.external_ids = response.external_ids;
    this.external_urls = response.external_urls;
    this.genres = response.genres;
    this.href = response.href;
    this.id = response.id;
    this.images = response.images;
    this.name = response.name;
    this.popularity = response.popularity;
    this.release_date = response.release_date;
    this.release_date_precision = response.release_date_precision;
    this.tracks = response.tracks;
    this.type = response.type;
    this.uri = response.uri;
  }
}
